In [1]:
import os

In [8]:
os.chdir("C:\\Users\\Asus\\Desktop\\Python_2")

In [9]:
os.chdir("C:/Users/Asus/Desktop/Python_2")

In [10]:
wd = os.getcwd()

In [11]:
wd

'C:\\Users\\Asus\\Desktop\\Python_2'

In [12]:
ls

 Volume in drive C is OS
 Volume Serial Number is E048-39BC

 Directory of C:\Users\Asus\Desktop\Python_2

22-04-2018  08:23    <DIR>          .
22-04-2018  08:23    <DIR>          ..
22-04-2018  08:23    <DIR>          .ipynb_checkpoints
24-03-2018  09:04               581 24_03_2018.ipynb
03-03-2018  09:16             5,155 BikeData.csv
03-03-2018  18:30            25,741 Class_2.ipynb
22-04-2018  08:22             1,837 Class16_data pre-processor.ipynb
03-03-2018  09:16            90,167 sampledata2.csv
03-03-2018  09:17            24,864 StudentSurvey.csv
               6 File(s)        148,345 bytes
               3 Dir(s)  825,543,266,304 bytes free


In [14]:
import numpy as np
import pandas as pda
import matplotlib.pyplot as plt

In [16]:
bike_data = pda.read_csv("BikeData.csv")

In [18]:
bike_data.head(10)

user_id  age gender  student  employed                 cyc_freq  distance  \
0        1   28      M        1         1                    Daily      3.25   
1        2   35      M        0         1                    Daily      1.11   
2        3   28      M        0         1                    Daily      5.59   
3        4   44      F        0         1   Less than once a month      3.24   
4        5   42      M        0         1   Several times per week      7.81   
5        6   36      M        0         1   Several times per week      3.00   
6        7   45      M        0         1   Several times per week     13.03   
7        8   54      M        0         1   Several times per week      6.21   
8        9   39      M        0         1   Several times per week     13.95   
9       10   44      M        0         0  Several times per month      7.40   

   time  speed  
0  15.0  13.00  
1   5.0  13.32  
2  23.0  14.58  
3  24.0   8.10  
4  26.0  18.02  
5  20.0   9.00  
6  51.0  15.33  
7  39.0   9.55  
8  50.0  16.74  
9  44.0  10.09

In [23]:
bike_data.dtypes

user_id       int64
age           int64
gender       object
student       int64
employed      int64
cyc_freq     object
distance    float64
time        float64
speed       float64
dtype: object

In [20]:
bike_data.shape()

TypeError: 'tuple' object is not callable

In [24]:
bike_data.head()

user_id  age gender  student  employed                cyc_freq  distance  \
0        1   28      M        1         1                   Daily      3.25   
1        2   35      M        0         1                   Daily      1.11   
2        3   28      M        0         1                   Daily      5.59   
3        4   44      F        0         1  Less than once a month      3.24   
4        5   42      M        0         1  Several times per week      7.81   

   time  speed  
0  15.0  13.00  
1   5.0  13.32  
2  23.0  14.58  
3  24.0   8.10  
4  26.0  18.02

In [25]:
bike_data = bike_data.rename( columns = {'user_id': 'ID_number', 'cyc_freq':'frequency'})

In [26]:
bike_data.head()

ID_number  age gender  student  employed               frequency  distance  \
0          1   28      M        1         1                   Daily      3.25   
1          2   35      M        0         1                   Daily      1.11   
2          3   28      M        0         1                   Daily      5.59   
3          4   44      F        0         1  Less than once a month      3.24   
4          5   42      M        0         1  Several times per week      7.81   

   time  speed  
0  15.0  13.00  
1   5.0  13.32  
2  23.0  14.58  
3  24.0   8.10  
4  26.0  18.02

In [29]:
mobile = pda.read_csv("New_data.csv")

In [55]:
mobile.head()

Name Gender  Age   Salary Purchase_flag
0      Ram      m   20  20000.0             Y
1     Sita      f   22  33000.0             N
2  Lakshya      m   18      NaN             Y
3     Hanu      m   60  10000.0             Y
4    Mytri      f   77  45000.0             Y

In [54]:
mobile = mobile[['Name','Gender','Age','Salary','Purchase_flag']]

In [31]:
mobile.shape

(9, 5)

In [32]:
mobile.dtypes

Name              object
Age                int64
Gender            object
Salary           float64
Purchase_flag     object
dtype: object

In [56]:
x = mobile.iloc[:,:-1].values


In [33]:
test = [1,2,4,6,99]

In [34]:
test

[1, 2, 4, 6, 99]

In [35]:
test[0]

1

In [36]:
test[2]

4

In [37]:
test[1,2]

TypeError: list indices must be integers or slices, not tuple

In [38]:
test[1:2]

[2]

In [39]:
test[1:3]

[2, 4]

In [40]:
test[-1]

99

In [58]:
x

array([['Ram', 'm', 20, 20000.0],
       ['Sita', 'f', 22, 33000.0],
       ['Lakshya', 'm', 18, nan],
       ['Hanu', 'm', 60, 10000.0],
       ['Mytri', 'f', 77, 45000.0],
       ['Revanth', 'm', 86, nan],
       ['Roger', 'f', 55, 37000.0],
       ['Khan', 'm', 29, 50000.0],
       ['Michel', 'f', 18, nan]], dtype=object)

In [57]:
y = mobile.iloc[:,-1].values

In [59]:
y

array(['Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y'], dtype=object)

In [60]:
from sklearn.preprocessing import Imputer as Im

In [48]:
?Imputer

In [61]:
Impute = Im(missing_values = "NaN", strategy = 'mean', axis = 0)  

In [66]:
Impute = Impute.fit(x[:,2:4])

In [67]:
x[:,2:4] = Impute.transform(x[:,2:4])

In [68]:
x

array([['Ram', 'm', 20.0, 20000.0],
       ['Sita', 'f', 22.0, 33000.0],
       ['Lakshya', 'm', 18.0, 32500.0],
       ['Hanu', 'm', 60.0, 10000.0],
       ['Mytri', 'f', 77.0, 45000.0],
       ['Revanth', 'm', 86.0, 32500.0],
       ['Roger', 'f', 55.0, 37000.0],
       ['Khan', 'm', 29.0, 50000.0],
       ['Michel', 'f', 18.0, 32500.0]], dtype=object)

In [69]:
mobile.head()

Name Gender  Age   Salary Purchase_flag
0      Ram      m   20  20000.0             Y
1     Sita      f   22  33000.0             N
2  Lakshya      m   18      NaN             Y
3     Hanu      m   60  10000.0             Y
4    Mytri      f   77  45000.0             Y

In [70]:
from sklearn.preprocessing import LabelEncoder

In [73]:
?LabelEncoder

In [72]:
x

array([['Ram', 'm', 20.0, 20000.0],
       ['Sita', 'f', 22.0, 33000.0],
       ['Lakshya', 'm', 18.0, 32500.0],
       ['Hanu', 'm', 60.0, 10000.0],
       ['Mytri', 'f', 77.0, 45000.0],
       ['Revanth', 'm', 86.0, 32500.0],
       ['Roger', 'f', 55.0, 37000.0],
       ['Khan', 'm', 29.0, 50000.0],
       ['Michel', 'f', 18.0, 32500.0]], dtype=object)

In [74]:
Label = LabelEncoder()

In [75]:
x[:,0] = Label.fit_transform(x[:,0])

In [76]:
x

array([[5, 'm', 20.0, 20000.0],
       [8, 'f', 22.0, 33000.0],
       [2, 'm', 18.0, 32500.0],
       [0, 'm', 60.0, 10000.0],
       [4, 'f', 77.0, 45000.0],
       [6, 'm', 86.0, 32500.0],
       [7, 'f', 55.0, 37000.0],
       [1, 'm', 29.0, 50000.0],
       [3, 'f', 18.0, 32500.0]], dtype=object)

In [77]:
x[:,1] = Label.fit_transform(x[:,1])

In [78]:
x

array([[5, 1, 20.0, 20000.0],
       [8, 0, 22.0, 33000.0],
       [2, 1, 18.0, 32500.0],
       [0, 1, 60.0, 10000.0],
       [4, 0, 77.0, 45000.0],
       [6, 1, 86.0, 32500.0],
       [7, 0, 55.0, 37000.0],
       [1, 1, 29.0, 50000.0],
       [3, 0, 18.0, 32500.0]], dtype=object)

In [89]:
from sklearn.cross_validation import train_test_split

In [86]:
!pip install scipy

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [91]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.20)

In [90]:
?train_test_split

In [92]:
x_train

array([[3, 0, 18.0, 32500.0],
       [4, 0, 77.0, 45000.0],
       [0, 1, 60.0, 10000.0],
       [2, 1, 18.0, 32500.0],
       [6, 1, 86.0, 32500.0],
       [5, 1, 20.0, 20000.0],
       [1, 1, 29.0, 50000.0]], dtype=object)

In [93]:
x_test

array([[7, 0, 55.0, 37000.0],
       [8, 0, 22.0, 33000.0]], dtype=object)

In [94]:
y_train

array(['Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N'], dtype=object)

In [95]:
y_test

array(['N', 'N'], dtype=object)